from __future__ import annotations

JOB_HEADERS = [
    "job_uid",
    "role_title",
    "company",
    "source",
    "job_url",
    "location",
    "work_mode",
    "posted_date",
    "freshness_days",
    "salary_min_thb",
    "salary_max_thb",
    "salary_text_raw",
    "salary_verified",
    "fit_score",
    "fit_reason",
    "data_analysis_exposure",
    "keywords_matched",
    "status",
    "last_seen_date",
    "added_date",
    "notes",
]

STATUS_FLOW = ["New", "Shortlisted", "Applied", "Interview", "Offer", "Reject"]

ROLE_KEYWORDS = {
    "chemist": [
        "chemist",
        "r&d chemist",
        "rd chemist",
        "analytical chemist",
        "qa chemist",
        "qc chemist",
        "quality assurance",
        "quality control",
        "laboratory",
        "lab analyst",
        "formulation",
        "iso/iec 17025",
        "method validation",
    ],
    "data": [
        "data",
        "analysis",
        "analytics",
        "dashboard",
        "excel",
        "power bi",
        "sql",
        "python",
        "vba",
        "reporting",
        "automation",
        "statistics",
        "kpi",
    ],
}

DATA_EXPOSURE_KEYWORDS = [
    "data analysis",
    "data analyst",
    "analytics",
    "dashboard",
    "reporting",
    "excel",
    "vba",
    "sql",
    "power bi",
    "python",
    "statistics",
    "automation",
    "visualization",
    "kpi",
]

SKILL_KEYWORDS = [
    "iso/iec 17025",
    "iso 17025",
    "iso",
    "method validation",
    "troubleshooting",
    "preventive maintenance",
    "formulation",
    "stability testing",
    "r&d",
    "analytical chemistry",
    "lab",
    "quality",
    "qa",
    "qc",
    "quality assurance",
    "quality control",
]

BANGKOK_NEARBY_KEYWORDS = [
    "bangkok",
    "krung thep",
    "กรุงเทพ",
    "nonthaburi",
    "นนทบุรี",
    "pathum",
    "ปทุม",
    "samut prakan",
    "สมุทรปราการ",
    "nakhon pathom",
    "นครปฐม",
]
